packages:
  - packages/*
  - platform/*

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@types/node': ^24.0.10
  body-data: ^2.0.4
  deeplx-lib: ^0.0.5
  eslint: ^9.30.1
  tsx: ^4.20.3
  typescript: ^5.8.3
  unbuild: ^3.5.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - workerd
